export enum ActionTypes {
    LOGIN_FIELD_CHANGE = 'LOGIN_FIELD_CHANGE',
    SIGNUP_FIELD_CHANGE = 'SIGNUP_FIELD_CHANGE',
    DO_LOGIN_REQUEST = 'DO_LOGIN_REQUEST',
    DO_LOGIN_SUCCESS = 'DO_LOGIN_SUCCESS',
    DO_LOGIN_FAILURE = 'DO_LOGIN_FAILURE',
    DO_SIGNUP_REQUEST = 'DO_SIGNUP_REQUEST',
    DO_SIGNUP_SUCCESS = 'DO_SIGNUP_SUCCESS',
    DO_SIGNUP_FAILURE = 'DO_SIGNUP_FAILURE',
    ADD_USER_DETAILS = 'ADD_USER_DETAILS'
}